### ISSUE TITLE
Keras takes long time to compile

### ISSUE THREAD

**Issue by dzhao123** [NTMC-Community/MatchZoo#605]
### Is your feature request related to a problem? Please describe.
Hi below is the model summary, it takes a long time to compile, is there any way to solve it?

`

```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
text_left (InputLayer)          (None, 10)           0                                            
__________________________________________________________________________________________________
text_right (InputLayer)         (None, 100)          0                                            
__________________________________________________________________________________________________
embedding (Embedding)           multiple             2819200     text_left[0][0]                  
                                                                 text_right[0][0]                 
__________________________________________________________________________________________________
dot_1 (Dot)                     (None, 10, 100)      0           embedding[0][0]                  
                                                                 embedding[1][0]                  
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 10, 1)        100         embedding[0][0]                  
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 10, 20)       0           dot_1[0][0]                      
__________________________________________________________________________________________________
attention_mask (Lambda)         (None, 10, 1)        0           dense_1[0][0]                    
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 10, 5)        105         lambda_1[0][0]                   
__________________________________________________________________________________________________
attention_probs (Lambda)        (None, 10, 1)        0           attention_mask[0][0]             
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 10, 1)        6           dense_2[0][0]                    
__________________________________________________________________________________________________
dot_2 (Dot)                     (None, 1, 1)         0           attention_probs[0][0]            
                                                                 dense_3[0][0]                    
__________________________________________________________________________________________________
flatten_1 (Flatten)             (None, 1)            0           dot_2[0][0]                      
__________________________________________________________________________________________________
dense_4 (Dense)                 (None, 1)            2           flatten_1[0][0]                  
==================================================================================================
Total params: 2,819,413
Trainable params: 2,819,413
Non-trainable params: 0
__________________________________________________________________________________________________
2019-01-31 16:43:54.953939: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-31 16:43:55.661802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:02:00.0
totalMemory: 11.91GiB freeMemory: 11.63GiB
2019-01-31 16:43:55.661991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-01-31 16:43:56.078310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-31 16:43:56.078447: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-01-31 16:43:56.078489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-01-31 16:43:56.078897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11249 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:02:00.0, compute capability: 6.0)
```

`

**Comment by uduse** [comment]
Please be specific. What model? How long? Did you monitor your memory and CPU usage? What's your hardware specs? What's the code you've written? What about just using keras but not matchzoo? What have you tried to solve the problem? e.t.c. Like I said in your last post, it is hard for us to help you if you do not provide enough information on your end.

**Comment by dzhao123** [comment]
```
Using TensorFlow backend.
Processing text_left with chain_transform of TokenizeUnit => LowercaseUnit => PuncRemovalUnit: 100%|████████████████████| 2/2 [00:00<00:00, 292.27it/s]
Processing text_right with chain_transform of TokenizeUnit => LowercaseUnit => PuncRemovalUnit: 100%|██████████████████| 4/4 [00:00<00:00, 1382.55it/s]
Processing text_left with chain_transform of TokenizeUnit => LowercaseUnit => PuncRemovalUnit: 100%|███████████████████| 2/2 [00:00<00:00, 2553.61it/s]
Processing text_right with chain_transform of TokenizeUnit => LowercaseUnit => PuncRemovalUnit: 100%|██████████████████| 4/4 [00:00<00:00, 1382.89it/s]
Processing length_left with len: 100%|█████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 5074.78it/s]
Processing length_right with len: 100%|███████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 10446.59it/s]
Processing text_left with transform: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 4319.57it/s]
Processing text_right with transform: 100%|████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 7394.10it/s]
Processing text_left with chain_transform of TokenizeUnit => LowercaseUnit => PuncRemovalUnit: 100%|███████████████████| 2/2 [00:00<00:00, 2504.81it/s]
Processing text_right with chain_transform of TokenizeUnit => LowercaseUnit => PuncRemovalUnit: 100%|██████████████████| 4/4 [00:00<00:00, 1383.35it/s]
Processing length_left with len: 100%|█████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 3418.34it/s]
Processing length_right with len: 100%|███████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 10538.45it/s]
Processing text_left with transform: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 4510.00it/s]
Processing text_right with transform: 100%|████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 7479.81it/s]
({'id_left': array(['Q188714', 'Q188714', 'Q188715', 'Q188715'], dtype='<U7'), 'text_left': array([['101', '9440', '1998', '25654', '2000', '2896', '2668', '5699',
        '102', '0'],
       ['101', '9440', '1998', '25654', '2000', '2896', '2668', '5699',
        '102', '0'],
       ['101', '9440', '1998', '25654', '2000', '2896', '2668', '5699',
        '102', '0'],
       ['101', '9440', '1998', '25654', '2000', '2896', '2668', '5699',
        '102', '0']], dtype='<U5'), 'length_left': array([9, 9, 9, 9]), 'id_right': array(['D1000052', 'D1000053', 'D1000054', 'D1000055'], dtype='<U8'), 'text_right': array([['101', '3422', '4664', '10826', '1024', '1037', '2130', '7965',
        '9440', '2097', '3426', '2152', '2668', '5699', '2065', '2017',
        '4521', '2205', '2172', '1012', '1037', '2191', '2469', '2169',
        '1997', '2115', '12278', '2038', '1996', '2168', '3815', '1997',
        '16480', '2015', '1012', '4468', '9440', '2152', '1999', '5699',
        '1024', '1037', '2070', '9440', '2000', '4468', '1024', '5699',
        '1010', '6861', '1010', '27467', '2229', '1010', '23353', '1010',
        '22619', '1010', '16324', '1010', '3180', '14904', '1998',
        '1012', '102', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
       ['101', '3422', '4664', '10826', '1024', '1037', '2130', '7965',
        '9440', '2097', '3426', '2152', '2668', '5699', '2065', '2017',
        '4521', '2205', '2172', '1012', '1037', '2191', '2469', '2169',
        '1997', '2115', '12278', '2038', '1996', '2168', '3815', '1997',
        '16480', '2015', '1012', '4468', '9440', '2152', '1999', '5699',
        '1024', '1037', '2070', '9440', '2000', '4468', '1024', '5699',
        '1010', '6861', '1010', '27467', '2229', '1010', '23353', '1010',
        '22619', '1010', '16324', '1010', '3180', '14904', '1998',
        '1012', '102', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
       ['101', '3422', '4664', '10826', '1024', '1037', '2130', '7965',
        '9440', '2097', '3426', '2152', '2668', '5699', '2065', '2017',
        '4521', '2205', '2172', '1012', '1037', '2191', '2469', '2169',
        '1997', '2115', '12278', '2038', '1996', '2168', '3815', '1997',
        '16480', '2015', '1012', '4468', '9440', '2152', '1999', '5699',
        '1024', '1037', '2070', '9440', '2000', '4468', '1024', '5699',
        '1010', '6861', '1010', '27467', '2229', '1010', '23353', '1010',
        '22619', '1010', '16324', '1010', '3180', '14904', '1998',
        '1012', '102', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
       ['101', '3422', '4664', '10826', '1024', '1037', '2130', '7965',
        '9440', '2097', '3426', '2152', '2668', '5699', '2065', '2017',
        '4521', '2205', '2172', '1012', '1037', '2191', '2469', '2169',
        '1997', '2115', '12278', '2038', '1996', '2168', '3815', '1997',
        '16480', '2015', '1012', '4468', '9440', '2152', '1999', '5699',
        '1024', '1037', '2070', '9440', '2000', '4468', '1024', '5699',
        '1010', '6861', '1010', '27467', '2229', '1010', '23353', '1010',
        '22619', '1010', '16324', '1010', '3180', '14904', '1998',
        '1012', '102', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']],
      dtype='<U5'), 'length_right': array([65, 65, 65, 65])}, array([[0.],
       [1.],
       [0.],
       [1.]], dtype=float32))
Parameter "name" set to DRMMTKS.
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
text_left (InputLayer)          (None, 10)           0                                            
__________________________________________________________________________________________________
text_right (InputLayer)         (None, 100)          0                                            
__________________________________________________________________________________________________
embedding (Embedding)           multiple             31255552    text_left[0][0]                  
                                                                 text_right[0][0]                 
__________________________________________________________________________________________________
dot_1 (Dot)                     (None, 10, 100)      0           embedding[0][0]                  
                                                                 embedding[1][0]                  
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 10, 1)        1024        embedding[0][0]                  
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 10, 20)       0           dot_1[0][0]                      
__________________________________________________________________________________________________
attention_mask (Lambda)         (None, 10, 1)        0           dense_1[0][0]                    
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 10, 5)        105         lambda_1[0][0]                   
__________________________________________________________________________________________________
attention_probs (Lambda)        (None, 10, 1)        0           attention_mask[0][0]             
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 10, 1)        6           dense_2[0][0]                    
__________________________________________________________________________________________________
dot_2 (Dot)                     (None, 1, 1)         0           attention_probs[0][0]            
                                                                 dense_3[0][0]                    
__________________________________________________________________________________________________
flatten_1 (Flatten)             (None, 1)            0           dot_2[0][0]                      
__________________________________________________________________________________________________
dense_4 (Dense)                 (None, 1)            2           flatten_1[0][0]                  
==================================================================================================
Total params: 31,256,689
Trainable params: 1,137
Non-trainable params: 31,255,552
__________________________________________________________________________________________________
/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matchzoo/embedding.py:114: FutureWarning: read_table is deprecated, use read_csv instead.
  quoting=csv.QUOTE_NONE)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 30522/30522 [00:00<00:00, 1334958.83it/s]
2019-02-03 11:07:43.463224: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-02-03 11:07:43.806956: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: Tesla V100-DGXS-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:07:00.0
totalMemory: 31.74GiB freeMemory: 1.10GiB
2019-02-03 11:07:44.144176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 1 with properties: 
name: Tesla V100-DGXS-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:08:00.0
totalMemory: 31.74GiB freeMemory: 1.15GiB
2019-02-03 11:07:44.484022: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 2 with properties: 
name: Tesla V100-DGXS-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:0e:00.0
totalMemory: 31.74GiB freeMemory: 1.15GiB
2019-02-03 11:07:44.827609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 3 with properties: 
name: Tesla V100-DGXS-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:0f:00.0
totalMemory: 31.74GiB freeMemory: 1.15GiB
2019-02-03 11:07:44.827678: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0, 1, 2, 3
2019-02-03 11:07:45.938802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-03 11:07:45.938834: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 1 2 3 
2019-02-03 11:07:45.938844: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N Y Y Y 
2019-02-03 11:07:45.938851: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 1:   Y N Y Y 
2019-02-03 11:07:45.938857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 2:   Y Y N Y 
2019-02-03 11:07:45.938863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 3:   Y Y Y N 
2019-02-03 11:07:45.939665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 832 MB memory) -> physical GPU (device: 0, name: Tesla V100-DGXS-32GB, pci bus id: 0000:07:00.0, compute capability: 7.0)
2019-02-03 11:07:45.951810: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 882 MB memory) -> physical GPU (device: 1, name: Tesla V100-DGXS-32GB, pci bus id: 0000:08:00.0, compute capability: 7.0)
2019-02-03 11:07:45.964502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 882 MB memory) -> physical GPU (device: 2, name: Tesla V100-DGXS-32GB, pci bus id: 0000:0e:00.0, compute capability: 7.0)
2019-02-03 11:07:45.977140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 882 MB memory) -> physical GPU (device: 3, name: Tesla V100-DGXS-32GB, pci bus id: 0000:0f:00.0, compute capability: 7.0)
labels: [1. 0.]
labels: [1. 0.]
[   id_left  id_right  label
1  Q188714  D1000053    1.0,    id_left  id_right  label
0  Q188714  D1000052    0.0,    id_left  id_right  label
3  Q188715  D1000055    1.0,    id_left  id_right  label
2  Q188715  D1000054    0.0]
                                                 text_left  length_left
id_left                                                                
Q188714  [101, 9440, 1998, 25654, 2000, 2896, 2668, 569...            9
Q188715  [101, 9440, 1998, 25654, 2000, 2896, 2668, 569...            9
                                                 text_right  length_right
id_right                                                                 
D1000052  [101, 3422, 4664, 10826, 1024, 1037, 2130, 796...            65
D1000053  [101, 3422, 4664, 10826, 1024, 1037, 2130, 796...            65
D1000054  [101, 3422, 4664, 10826, 1024, 1037, 2130, 796...            65
D1000055  [101, 3422, 4664, 10826, 1024, 1037, 2130, 796...            65
   id_left  id_right  label
0  Q188714  D1000053    1.0
1  Q188714  D1000052    0.0
2  Q188715  D1000055    1.0
3  Q188715  D1000054    0.0
Epoch 1/30
Traceback (most recent call last):
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,1] vs. shape[4] = [0,1]
	 [[Node: loss/dense_4_loss/concat_1 = ConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](loss/dense_4_loss/lambda_3/strided_slice, loss/dense_4_loss/lambda_5/strided_slice, loss/dense_4_loss/lambda_7/strided_slice, loss/dense_4_loss/lambda_9/strided_slice, loss/dense_4_loss/lambda_11/strided_slice, loss/dense_4_loss/concat_1/axis)]]
	 [[Node: loss/mul/_87 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_886_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "try.py", line 105, in <module>
    history = model.fit_generator(train_generator, epochs=30, callbacks=[evaluate], workers=30, use_multiprocessing=True)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matchzoo/engine/base_model.py", line 266, in fit_generator
    verbose=verbose, **kwargs
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2721, in __call__
    return self._legacy_call(inputs)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2693, in _legacy_call
    **self.session_kwargs)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,1] vs. shape[4] = [0,1]
	 [[Node: loss/dense_4_loss/concat_1 = ConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](loss/dense_4_loss/lambda_3/strided_slice, loss/dense_4_loss/lambda_5/strided_slice, loss/dense_4_loss/lambda_7/strided_slice, loss/dense_4_loss/lambda_9/strided_slice, loss/dense_4_loss/lambda_11/strided_slice, loss/dense_4_loss/concat_1/axis)]]
	 [[Node: loss/mul/_87 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_886_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'loss/dense_4_loss/concat_1', defined at:
  File "try.py", line 74, in <module>
    model.compile()
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matchzoo/engine/base_model.py", line 210, in compile
    loss=self._params['task'].loss)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training.py", line 342, in compile
    sample_weight, mask)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training_utils.py", line 404, in weighted
    score_array = fn(y_true, y_pred)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matchzoo/losses/rank_cross_entropy_loss.py", line 50, in __call__
    labels = K.concatenate(labels, axis=-1)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1956, in concatenate
    return tf.concat([to_dense(x) for x in tensors], axis)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1181, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 949, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/home/dzhao123/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [1,1] vs. shape[4] = [0,1]
	 [[Node: loss/dense_4_loss/concat_1 = ConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](loss/dense_4_loss/lambda_3/strided_slice, loss/dense_4_loss/lambda_5/strided_slice, loss/dense_4_loss/lambda_7/strided_slice, loss/dense_4_loss/lambda_9/strided_slice, loss/dense_4_loss/lambda_11/strided_slice, loss/dense_4_loss/concat_1/axis)]]
	 [[Node: loss/mul/_87 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_886_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

**Comment by uduse** [comment]
So you're having a different problem now? If you want to try a smaller sample, always use `data_pack[:num_samples]` to create a subset of the entire data pack. Also, there's a recent bug fix #614, maybe this is related? It is also helpful to do a `print(model.params)` so we know how the model is built.

**Comment by dzhao123** [comment]
@uduse Thanks for reply. I am trying to use matchzoo as a tool for my research, but currently is seems like a toy. I was trying to say that if take keras as a high level tf.estimator, it should combine with tf.data to maximize its power. Besides tensorlayer is a really good high level software on tensorflow, which has its own data processing pipelines, intergrating much better with tensorflow, beatiful code and easy to debug, so just some suggestion. Thanks for your patience.

**Comment by uduse** [comment]
MatchZoo 1 models were developed in keras so MatchZoo 2 models use keras as well for an easier transition. MatchZoo's data processing pipeline wraps over pandas, which is also a top choice for data processing, and I do not see much advantage using tensorlayer instead. I agree that some part of the project is like a toy: the real meaning of MatchZoo's existence are models, metrics, and losses (these are things text matching researchers care for). These parts are designed in a way that they could be used without other modules, which means if you like tensorlayer better, you may do all the preprocessing steps in tensorlayer, as long as you set MatchZoo model parameters correctly and feed them the right data.

**Comment by dzhao123** [comment]
@uduse Thanks for your help.
