### ISSUE TITLE
mz.PairDataGenerator makes error

### ISSUE THREAD

**Issue by wanghaoyu0408** [NTMC-Community/MatchZoo#647]
train_generator = mz.PairDataGenerator(train_pack_processed, num_dup=1, num_neg=4, batch_size=64, shuffle=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data1/home/haoyu/MatchZoo-master/matchzoo/data_generator/pair_data_generator.py", line 58, in __init__
    num_neg)
  File "/data1/home/haoyu/MatchZoo-master/matchzoo/data_generator/pair_data_generator.py", line 87, in reorganize_data_pack
    groups = data_pack.relation.sort_values(
AttributeError: 'DSSMPreprocessor' object has no attribute 'relation'

how can I fix it? Thanks!

**Comment by uduse** [comment]
Please use our issue template. Normally I do not enforce this but your question is so simple that I doubt you invested effort trying. Use the issue template so I know you spent at least 5 mins on this, and then I will be glad to help you.
