### ISSUE TITLE
Is there a tutorial on the DIIN model?

### ISSUE THREAD

**Issue by ouyaya** [NTMC-Community/MatchZoo#822]
When I called the model according to the hyperparameters given by the model, a problem occurred“ValueError: Layer weight shape (10000, 300) not compatible with provided weight shape (33905, 300)”.
So I changed the hyperparameter 'embedding_input_dim' to 33905, but another problem appeared“tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[1200,0] = 184 is not in [0, 100)
	 [[{{node time_distributed_1_1/embedding_1/embedding_lookup}}]]”

**Comment by uduse** [comment]
#821 Does this help?

**Comment by ouyaya** [comment]
I referenced these hyperparameters, but found that the following hyperparameter reports an error. model.params ['embedding_input_dim'] = 10000
An error message indicates that this hyperparameter should be set to 33905. However, another error occurred after I changed it to 33905. I was wondering if the code in the other calling part is wrong.So do you have the tutorial code to call this model correctly?

**Comment by uduse** [comment]
@ouyaya Did you use the correct preprocessor?

**Comment by ouyaya** [comment]
Yes, I used the processing method in diin_preprocessor.py

**Comment by uduse** [comment]
I need more information, can you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by ouyaya** [comment]
[matchzoo_diin.txt](https://github.com/NTMC-Community/MatchZoo/files/4362559/matchzoo_diin.txt)
When I run this calling code, I get the following error:
Traceback (most recent call last):
  File "E:/Paper/keras_wiki/matchzoo_diin.py", line 60, in <module>
    model.load_embedding_matrix(embedding_matrix)
  File "F:\Python\lib\site-packages\matchzoo\engine\base_model.py", line 469, in load_embedding_matrix
    self.get_embedding_layer(name).set_weights([embedding_matrix])
  File "F:\Python\lib\site-packages\keras\engine\base_layer.py", line 1126, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (10000, 300) not compatible with provided weight shape (33905, 300)

**Comment by uduse** [comment]
In addition to the other change you made, also set the embedding input dimension for char embedding:
`model.params['char_embedding_input_dim'] = len(diin_preprocessor.context['char_unit'].state['term_index'])`

**Comment by ouyaya** [comment]
Thank you for your answer, this problem has been solved according to your prompt. But when I use the wiki dataset to train this model, the loss value will become higher and higher. I do n’t know if it is a problem with the model code or a task I deal with. The task I deal with is ‘ranking’.

**Comment by uduse** [comment]
The reason that the model is in `contrib` is it is not fully tested, so I am not sure why this is happening. @caiyinqiong is the author and maybe she has something to say?

**Comment by ouyaya** [comment]
Do I need to tune the hyperparameters without hyperspace in the given model for the new dataset?

**Comment by uduse** [comment]
If a parameter don't have a hyperspace then it won't be tuned and it will just use the default value. It's always a good idea to tune your models on new datasets. You can do this by either manually adjusting things, or using the auto tuner.

**Comment by ouyaya** [comment]
I mean, do I need to add hyperspace to those hyperparameters that do not have hyperspace, and then use the auto-tuner to adjust all the parameters? If I adjust all the parameters, will it affect the initial model mentioned in the paper, because I want to do comparison experiments with my own paper model.

**Comment by uduse** [comment]
@ouyaya If you just want a baseline, then yes, don't add extra hyperspaces, just use the default ones. You don't even need to tune the model, just run the model as it is. In addition, you can also tune the model then call the model a "fine-tuned" baseline.
