### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by lovekittynine** [NTMC-Community/MatchZoo#841]
### Describe the bug
error occurs when import matchzoo

### Describe your attempts
>>> import matchzoo as mz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/python_venv/lib/python3.5/site-packages/matchzoo/__init__.py", line 13, in <module>
    from .data_pack import DataPack
  File "/app/python_venv/lib/python3.5/site-packages/matchzoo/data_pack/__init__.py", line 1, in <module>
    from .data_pack import DataPack, load_data_pack
  File "/app/python_venv/lib/python3.5/site-packages/matchzoo/data_pack/data_pack.py", line 215
    f'{data_file_path} already exist, fail to save')
                                                  ^
SyntaxError: invalid syntax

### Context
centos7
matchzoo 2.2.0

**Comment by takiholadi** [comment]
Try Python 3.6 or 3.7, not 3.5.

The line with SyntaxError you provided is so-called "f-string", it is available since Python 3.6.
